FROM continuumio/miniconda3

LABEL maintainer "Jason Gullifer <jason.gullifer@mail.mcgill.ca>"

# Install python packages
RUN conda install \
		jupyter \
        pandas \ 
        statsmodels \ 
        matplotlib \ 
        seaborn

RUN conda install -c conda-forge xgboost

ENV PATH /opt/conda/bin:$PATH

# Expose port for jupyter
EXPOSE 8888

# Setup File System
#RUN mkdir home
ENV HOME=/home
ENV SHELL=/bin/bash
VOLUME /home
WORKDIR /home

CMD ["sh", "-c", "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"]
#CMD ["/bin/bash"]