FROM continuumio/miniconda3

LABEL maintainer "Jason Gullifer <jason.gullifer@mail.mcgill.ca>"

ENV PATH /opt/conda/bin:$PATH

# Expose port for jupyter
EXPOSE 8888

# Setup File System
#RUN mkdir home/analyst
ENV HOME=/home/analyst
ENV SHELL=/bin/bash
VOLUME /home/analyst
WORKDIR /home/analyst

RUN useradd analyst \
  && echo "analyst:analyst" | chpasswd \
	&& chown analyst:analyst /home/analyst \
	&& addgroup analyst staff

# Install python packages
RUN conda install \
		jupyter \
        pandas \ 
        statsmodels \ 
        matplotlib \ 
        seaborn

RUN conda install -c conda-forge xgboost

USER analyst 

CMD ["sh", "-c", "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"]
#CMD ["/bin/bash"]

USER root