FROM rocker/tidyverse

LABEL maintainer "Jason Gullifer <jason.gullifer@mail.mcgill.ca>"

# Setup File System
#RUN mkdir home/analyst
ENV HOME=/home/analyst
ENV SHELL=/bin/bash
VOLUME /home/analyst
WORKDIR /home/analyst

RUN useradd analyst \
  	&& echo "analyst:analyst" | chpasswd \
	&& chown analyst:analyst /home/analyst \
	&& addgroup analyst staff
	
RUN install2.r -e  bookdown rmarkdown knitr lme4 lattice \
	Matrix devtools lmerTest GGally VWPre plotfunctions ff \ 
	data.table tables effects factoextra MuMIn \
	xgboost mlr caret parallelMap Ckmeans.1d.dp DiagrammeR

RUN R -e "devtools::install_github(c('crsh/papaja', 'strengejacke/sjPlot', 'jasongullifer/languageentropy', 'jasongullifer/convenience'))"
