FROM rocker/tidyverse

LABEL maintainer "Jason Gullifer <jason.gullifer@mail.mcgill.ca>"

RUN install2.r -e  bookdown rmarkdown knitr lme4 lattice Matrix devtools lmerTest GGally

RUN R -e "devtools::install_github('crsh/papaja')"
RUN R -e "devtools::install_github('strengejacke/sjPlot')"

# Setup File System
#RUN mkdir home/analyst
ENV HOME=/home/analyst
ENV SHELL=/bin/bash
VOLUME /home/analyst
WORKDIR /home/analyst

RUN useradd analyst \
  && echo "analyst:analyst" | chpasswd \
	&& chown analyst:analyst /home/analyst \
	&& addgroup analyst staff